const communities = [
    {
        id: "1",
        name: "Tech Enthusiasts Club",
        description: "A community for tech lovers to discuss trends, share knowledge, and collaborate on projects.",
        members: 1200,
        events: "10+ per month",
        location: "Online",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "2",
        name: "Fitness Warriors",
        description: "Join us to stay fit, share workout tips, and participate in group challenges.",
        members: 850,
        events: "5 per month",
        location: "Local Gym",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "3",
        name: "Art & Creativity Hub",
        description: "A space for artists to showcase their work, learn new skills, and collaborate on creative projects.",
        members: 500,
        events: "Monthly exhibitions",
        location: "City Center",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "4",
        name: "Startup Innovators",
        description: "Connect with entrepreneurs and innovators to build, learn, and grow startups together.",
        members: 3000,
        events: "Weekly webinars",
        location: "Online",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "5",
        name: "Gaming Legends",
        description: "A paradise for gamers to compete, stream, and discuss the latest in the gaming world.",
        members: 2000,
        events: "Tournaments every weekend",
        location: "Virtual",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "6",
        name: "Cooking Club",
        description: "Share recipes, learn new cooking techniques, and connect with food enthusiasts.",
        members: 600,
        events: "Bi-weekly workshops",
        location: "Community Hall",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "7",
        name: "Travel Explorers",
        description: "Plan trips, share experiences, and explore the world with fellow travelers.",
        members: 1000,
        events: "Quarterly expeditions",
        location: "Global",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "8",
        name: "Music Lovers",
        description: "Jam sessions, music theory, and collaboration for budding and professional musicians.",
        members: 750,
        events: "Open mic nights",
        location: "Downtown Studio",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "9",
        name: "Book Readers",
        description: "Join book clubs, share reviews, and discuss your favorite reads.",
        members: 400,
        events: "Monthly meet-ups",
        location: "Library",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "1",
        name: "Photography Masters",
        description: "Learn and improve your photography skills, share your work, and get feedback.",
        members: 950,
        events: "Weekend photo walks",
        location: "Outdoor",
        image: "https://via.placeholder.com/150",
    },
];


export default communities